### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by rayto298** [rayto298/railsbeya#14]
### 概要
"Issueベースの開発"レビュー依頼のissueです。

### GitHub Project
https://github.com/users/rayto298/projects/5/views/1

### 実装予定の機能
- [ ] ユーザ登録
- [ ] ユーザ編集機能
- [ ] ログイン機能
- [ ] アプリ投稿機能
- [ ] アプリ検索機能
- [ ] アプリ編集機能
- [ ] Xのポスト表示機能
- [ ] 技術記事検索機能
- [ ] YouTube動画検索機能

### 必要なページ
- [ ] トップページ
- [ ] ログイン画面
- [ ] ユーザ登録画面
- [ ] ユーザ詳細画面
- [ ] ユーザ編集画面
- [ ] アプリ投稿画面
- [ ] アプリ検索画面
- [ ] アプリ詳細画面
- [ ] アプリ編集画面
- [ ] 技術記事検索画面
- [ ] YouTube動画検索画面

### 補足
極力MVPリリースまでに上記の機能を実装したいと考えていますが、7/2が卒業予定日で日にちがあまりなく、進捗次第では少しMVPリリース時の機能を減らす可能性があると思います。卒業予定日から少し余裕を持った6/26をMVPリリース予定日としています。

**Comment by Tsuchiya2** [comment]
概ね良いかと思います。LGTMです。

以下はMVP後で良いかと思いました。

- Xのポスト
- ユーザー編集
